version: '3'
services:
  web:
    image: norin/mne:1.0
    restart: always
    depends_on:
      - db
    environment:
      RAILS_ENV: production
    ports:
      - '3000:3000'
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './data:/var/lib/mysql'
