default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: mne_dev

test:
  <<: *default
  database: mne_test

production:
  <<: *default
  database: mne_prod
